# General messages
general-messages:
  reload-message: "&aSuccessfully reloaded plugin in &e{time}&ams!"
  only-players: "&cI'm sorry, but only players are allowed to perform this command."
  player-not-found: "&cCould not find specified player."

# PvP toggle messages
pvp-enabled: "&aSuccessfully enabled pvp!"
pvp-disabled: "&eSuccessfully disabled pvp!"

# PvP toggle messages for other players
pvp-enabled-other: "&aSuccessfully enabled pvp for &e{target}&a!"
pvp-disabled-other: "&eSuccessfully disabled pvp for &e{target}!"

# Format death message?
format-death-message: true

# Death message
death-message: "&c{victim} &7was slain by &a{killer} &7(&c{health}&7)"

# Should PvP be enabled by default?
pvp-enabled-by-default: false

# Console commands that get
# executed after pvp enables
# without the slash.

# Set to [] to disable
on-pvp-enable-console-commands: []

# Console commands that get
# executed after pvp disables
# without the slash.

# Set to [] to disable
on-pvp-disable-console-commands: []

# Save player inventory when they enable pvp
# and re-apply it when they disable pvp?
cached-inventories: false

# Save player location when they enable pvp
# and re-teleport them there when they disable pvp?
cached-locations: false

# Allow health to go down in pvp?
# If this option is enabled, then
# the player will appear to be taking damage
# but their health will not go down
stay-at-max-health: false

# PlaceholderAPI "%pvptoggler_pvp%" placeholder output
# true; the output if PvP is on
# false; the output if PvP is off
placeholders-output:
  true: "On"
  false: "Off"

# MySQL Connection
# Use MySQL if you want to
# sync PvP statuses
mysql-connection:
  enabled: false
  address: "127.0.0.1"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "secretive"
